import pandas as pd
datos= pd.read_csv('movies2.csv')
df= pd.DataFrame(datos)
print(df.head())
print("PELÍCULA CON MÁS DURACIÓN: ")
print(df['duration'].max())
minutos= df['duration'].max()
print("Horas: ", minutos/60)
print("LA PELÍCULA QUE DURA MÁS ES: ")
print(df['duration'].idxmax())
max_duration_index= df['duration'].idxmax()
print(df.loc[10, 'movie_title'])
print("COMPARACIÓN DE LIKES POR GÉNERO")
df1= df.groupby(['genres'])[['movie_facebook_likes']].sum()
print(df1)
print("EL GÉNERO CON MÁS LIKES")
likes= df.groupby(['genres'])[['movie_facebook_likes']].sum()
print("Con: ", likes['movie_facebook_likes'].max(), " likes ")